import net.dv8tion.jda.api.events.message.MessageReceivedEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;

public class Problem extends ListenerAdapter {

  @Override
  public void onMessageReceived(MessageReceivedEvent event) {
    String msg = event.getMessage().getContentRaw();
      switch(msg){
      case Constants.PREFIX + "p1": event.getChannel().sendMessage(Problems.p1).queue();
        break;
      case Constants.PREFIX + "p2": event.getChannel().sendMessage(Problems.p2).queue();
                                    event.getChannel().sendMessage(Problems.p2_2).queue();
        break;
      case Constants.PREFIX + "p3": event.getChannel().sendMessage(Problems.p3).queue();
        break;
      case Constants.PREFIX + "p4": event.getChannel().sendMessage(Problems.p4).queue();
        break;
      case Constants.PREFIX + "p5": event.getChannel().sendMessage(Problems.p5).queue();
        break;
      case Constants.PREFIX + "p6": event.getChannel().sendMessage(Problems.p6).queue();
        break;
      case Constants.PREFIX + "p7": event.getChannel().sendMessage(Problems.p7).queue();
        break;
      case Constants.PREFIX + "p8": event.getChannel().sendMessage(Problems.p8).queue();
        break;
      case Constants.PREFIX + "p9": event.getChannel().sendMessage(Problems.p9).queue();
        break;
      case Constants.PREFIX + "p10": event.getChannel().sendMessage(Problems.p10).queue();
        break;
      case Constants.PREFIX + "p11": event.getChannel().sendMessage(Problems.p11).queue();
        break;
      case Constants.PREFIX + "p12": event.getChannel().sendMessage(Problems.p12).queue();
        break;
      case Constants.PREFIX + "p13": event.getChannel().sendMessage(Problems.p13).queue();
        break;
      case Constants.PREFIX + "p14": event.getChannel().sendMessage(Problems.p14).queue();
        break;
      case Constants.PREFIX + "p15": event.getChannel().sendMessage(Problems.p15).queue();
        break;
      case Constants.PREFIX + "p16": event.getChannel().sendMessage(Problems.p16).queue();
        break;
      case Constants.PREFIX + "p17": event.getChannel().sendMessage(Problems.p17).queue();
        break;
      case Constants.PREFIX + "p18": event.getChannel().sendMessage(Problems.p18).queue();
        break;
      case Constants.PREFIX + "p19": event.getChannel().sendMessage(Problems.p19).queue();
        break;
      case Constants.PREFIX + "p20": event.getChannel().sendMessage(Problems.p20).queue();
        break;
      case Constants.PREFIX + "p21": event.getChannel().sendMessage(Problems.p21).queue();
        break;
      case Constants.PREFIX + "p22": event.getChannel().sendMessage(Problems.p22).queue();
        break;
      case Constants.PREFIX + "p23": event.getChannel().sendMessage(Problems.p23).queue();
        break;
      case Constants.PREFIX + "p24": event.getChannel().sendMessage(Problems.p24).queue();
        break;
      case Constants.PREFIX + "p25": event.getChannel().sendMessage(Problems.p25).queue();
        break;
      case Constants.PREFIX + "p26": event.getChannel().sendMessage(Problems.p26).queue();
        break;
      case Constants.PREFIX + "p27": event.getChannel().sendMessage(Problems.p27).queue();
        break;
      case Constants.PREFIX + "p28": event.getChannel().sendMessage(Problems.p28).queue();
        break;
      case Constants.PREFIX + "p29": event.getChannel().sendMessage(Problems.p29).queue();
        break;
      case Constants.PREFIX + "p30": event.getChannel().sendMessage(Problems.p30).queue();
        break;
      case Constants.PREFIX + "p31": event.getChannel().sendMessage(Problems.p31).queue();
        break;
      case Constants.PREFIX + "p32": event.getChannel().sendMessage(Problems.p32).queue();
        break;
      case Constants.PREFIX + "p33": event.getChannel().sendMessage(Problems.p33).queue();
        break;
      case Constants.PREFIX + "p34": event.getChannel().sendMessage(Problems.p34).queue();
        break;
      case Constants.PREFIX + "p35": event.getChannel().sendMessage(Problems.p35).queue();
        break;
      case Constants.PREFIX + "p36": event.getChannel().sendMessage(Problems.p36).queue();
        break;
      case Constants.PREFIX + "p37": event.getChannel().sendMessage(Problems.p37).queue();
        break;
      case Constants.PREFIX + "p38": event.getChannel().sendMessage(Problems.p38).queue();
        break;
      case Constants.PREFIX + "p39": event.getChannel().sendMessage(Problems.p39).queue();
        break;
      case Constants.PREFIX + "p40": event.getChannel().sendMessage(Problems.p40).queue();
        break;
      case Constants.PREFIX + "p41": event.getChannel().sendMessage(Problems.p41).queue();
        break;
      case Constants.PREFIX + "p42": event.getChannel().sendMessage(Problems.p42).queue();
        break;
      case Constants.PREFIX + "p43": event.getChannel().sendMessage(Problems.p43).queue();
        break;
      case Constants.PREFIX + "p44": event.getChannel().sendMessage(Problems.p44).queue();
        break;
      case Constants.PREFIX + "p45": event.getChannel().sendMessage(Problems.p45).queue();
                                     event.getChannel().sendMessage(Problems.p45_2).queue();
        break;
      case Constants.PREFIX + "p46": event.getChannel().sendMessage(Problems.p46).queue();
        break;
      case Constants.PREFIX + "p47": event.getChannel().sendMessage(Problems.p47).queue();
        break;
      case Constants.PREFIX + "p48": event.getChannel().sendMessage(Problems.p48).queue();
        break;
      case Constants.PREFIX + "p49": event.getChannel().sendMessage(Problems.p49).queue();
        break;
      case Constants.PREFIX + "p50": event.getChannel().sendMessage(Problems.p50).queue();
        break;
      case Constants.PREFIX + "p51": event.getChannel().sendMessage(Problems.p51).queue();
        break;
      case Constants.PREFIX + "p52": event.getChannel().sendMessage(Problems.p52).queue();
        break;
      case Constants.PREFIX + "p53": event.getChannel().sendMessage(Problems.p53).queue();
        break;
      case Constants.PREFIX + "p54": event.getChannel().sendMessage(Problems.p54).queue();
        break;
      case Constants.PREFIX + "p55": event.getChannel().sendMessage(Problems.p55).queue();
        break;
      case Constants.PREFIX + "p56": event.getChannel().sendMessage(Problems.p56).queue();
        break;
      case Constants.PREFIX + "p57": event.getChannel().sendMessage(Problems.p57).queue();
        break;
      case Constants.PREFIX + "p58": event.getChannel().sendMessage(Problems.p58).queue();
        break;
      case Constants.PREFIX + "p59": event.getChannel().sendMessage(Problems.p59).queue();
        break;
      case Constants.PREFIX + "p60": event.getChannel().sendMessage(Problems.p60).queue();
        break;
      case Constants.PREFIX + "p61": event.getChannel().sendMessage(Problems.p61).queue();
        break;
      case Constants.PREFIX + "p62": event.getChannel().sendMessage(Problems.p62).queue();
        break;
      case Constants.PREFIX + "p63": event.getChannel().sendMessage(Problems.p63).queue();
        break;
      case Constants.PREFIX + "p64": event.getChannel().sendMessage(Problems.p64).queue();
        break;
      case Constants.PREFIX + "p65": event.getChannel().sendMessage(Problems.p65).queue();
        break;
      case Constants.PREFIX + "p66": event.getChannel().sendMessage(Problems.p66).queue();
        break;
      case Constants.PREFIX + "p67": event.getChannel().sendMessage(Problems.p67).queue();
        break;
      case Constants.PREFIX + "p68": event.getChannel().sendMessage(Problems.p68).queue();
        break;
      case Constants.PREFIX + "p69": event.getChannel().sendMessage(Problems.p69).queue();
        break;
      case Constants.PREFIX + "p70": event.getChannel().sendMessage(Problems.p70).queue();
        break;
      case Constants.PREFIX + "p71": event.getChannel().sendMessage(Problems.p71).queue();
        break;
      case Constants.PREFIX + "p72": event.getChannel().sendMessage(Problems.p72).queue();
        break;
      case Constants.PREFIX + "p73": event.getChannel().sendMessage(Problems.p73).queue();
        break;
      case Constants.PREFIX + "p74": event.getChannel().sendMessage(Problems.p74).queue();
        break;
      case Constants.PREFIX + "p75": event.getChannel().sendMessage(Problems.p75).queue();
        break;
      case Constants.PREFIX + "p76": event.getChannel().sendMessage(Problems.p76).queue();
        break;
      case Constants.PREFIX + "p77": event.getChannel().sendMessage(Problems.p77).queue();
        break;
      case Constants.PREFIX + "p78": event.getChannel().sendMessage(Problems.p78).queue();
        break;
      case Constants.PREFIX + "p79": event.getChannel().sendMessage(Problems.p79).queue();
        break;
      case Constants.PREFIX + "p80": event.getChannel().sendMessage(Problems.p80).queue();
        break;
      case Constants.PREFIX + "p81": event.getChannel().sendMessage(Problems.p81).queue();
        break;
      case Constants.PREFIX + "p82": event.getChannel().sendMessage(Problems.p82).queue();
        break;
      case Constants.PREFIX + "p83": event.getChannel().sendMessage(Problems.p83).queue();
        break;
      case Constants.PREFIX + "p84": event.getChannel().sendMessage(Problems.p84).queue();
        break;
      case Constants.PREFIX + "p85": event.getChannel().sendMessage(Problems.p85).queue();
        break;
      case Constants.PREFIX + "p86": event.getChannel().sendMessage(Problems.p86).queue();
        break;
      case Constants.PREFIX + "p87": event.getChannel().sendMessage(Problems.p87).queue();
        break;
      case Constants.PREFIX + "p88": event.getChannel().sendMessage(Problems.p88).queue();
        break;
      case Constants.PREFIX + "p89": event.getChannel().sendMessage(Problems.p89).queue();
        break;
      case Constants.PREFIX + "p90": event.getChannel().sendMessage(Problems.p90).queue();
        break;
      case Constants.PREFIX + "p91": event.getChannel().sendMessage(Problems.p91).queue();
        break;
      case Constants.PREFIX + "p92": event.getChannel().sendMessage(Problems.p92).queue();
        break;
      case Constants.PREFIX + "p93": event.getChannel().sendMessage(Problems.p93).queue();
        break;
      case Constants.PREFIX + "p94": event.getChannel().sendMessage(Problems.p94).queue();
        break;
      case Constants.PREFIX + "p95": event.getChannel().sendMessage(Problems.p95).queue();
        break;
      case Constants.PREFIX + "p96": event.getChannel().sendMessage(Problems.p96).queue();
        break;
      case Constants.PREFIX + "p97": event.getChannel().sendMessage(Problems.p97).queue();
        break;
      case Constants.PREFIX + "p98": event.getChannel().sendMessage(Problems.p98).queue();
        break;
      case Constants.PREFIX + "p99": event.getChannel().sendMessage(Problems.p99).queue();
        break;
      case Constants.PREFIX + "p100": event.getChannel().sendMessage(Problems.p100).queue();
        break;
        
    
    }
  }
}